### PR TITLE
Expanded plsr JL

### PR DESCRIPTION
**Pull request by JulienLamour**
A lot of description is on the commits. We can talk about it when you want

### CODE REVIEW

**Comment by serbinsh** [comment]
@JulienLamour by chance are the changes in this PR also in the edits to this branch? https://github.com/TESTgroup-BNL/How_to_PLSR/tree/expanded_plsr

**Comment by JulienLamour** [comment]
Yes!

**Comment by serbinsh** [comment]
OK So I just need to merge this PR then correct and we can then get rid of that other branch....correct?

**Comment by JulienLamour** [comment]
Yes correct

**Comment by serbinsh** [comment]
@JulienLamour I am having a hard time trying to differentiate the three approaches.  Could you possibly update this PR and just rename your new script here from "R_Scripts/expanded_spectra-trait_plsr_example.R " to something like "R_Scripts/expanded_spectra-trait_plsr_example-JL.R" and the push the changes into the same branch so it updates this PR? Then I can merge and keep all three versions and then work on testing them all and figure out a good 3-way compromise that you and @neo0351 can review?

**Comment by serbinsh** [comment]
Sorry i know thats not proper git but I think I need a way to run all three and compare so i can make sure I understand all the proposed changes

**Comment by serbinsh** [comment]
No @JulienLamour you have to change the name of the actual script file in your git branch for this pull request. you have to rename the actual file not the title of this PR

**Pull request merged**
